name: Generate APK

on:
  push:
      branches: [master]

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grand execute permissions for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew clean testDebug

  destribute:
    name: Generate APK
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Install dependencies
        run: ./gradlew dependencies

      - name: Version Bump
        uses: chkfung/android-version-actions@v1.2.3
        with:
            gradlePath: app/build.gradle.kts
            versionCode: ${{ github.run_number }}

      - name: Build release APK
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk

      - name: Sign APK
        run: |
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
          -keystore $ANDROID_KEYSTORE \
          -storepass $KEYSTORE_PASSWORD \
          -keypass $KEY_PASSWORD \
          app/build/outputs/apk/release/app-release.apk $KEY_ALIAS