name: Generate APK

on:
  push:
      branches: [master]

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grand execute permissions for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew clean testDebug

  destribute:
    name: Generate APK
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grand execute permissions for gradlew
        run: chmod +x gradlew

      - name: Install dependencies
        run: ./gradlew dependencies

      - name: Version Bump
        uses: chkfung/android-version-actions@v1.2.3
        with:
            gradlePath: app/build.gradle.kts
            versionCode: ${{ github.run_number }}

      - name: Decode Base64 keystore
        env:
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
        run: |
            echo "$ANDROID_KEYSTORE" | base64 --decode > keystore.jks

      - name: Build release APK
        run: ./gradlew assembleRelease

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.2

      - name: Debug APK path
        run: ls -la $GITHUB_WORKSPACE/app/build/outputs/apk/release/

      - name: Sign APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        run: |
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
          -keystore keystore.jks \
          -storepass "$KEYSTORE_PASSWORD" \
          -keypass "$KEY_PASSWORD" \
          app/build/outputs/apk/release/app-release-unsigned.apk "$KEY_ALIAS"

      - name: Verify signed APK
        run: |
          $ANDROID_HOME/build-tools/33.0.2/apksigner verify \
          app/build/outputs/apk/release/app-release-aligned.apk

      - name: Cleanup keystore
        run: rm keystore.jks

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: signed-apk
          path: app/build/outputs/apk/release/*.apk